language: php
php:
  - '7.0'
  - '7.1'
  - '5.4'
  - '5.5'
  - '5.6'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: '7.1'
  - php: '5.4'
  - php: '5.5'
  - php: '5.6'
  - php: hhvm
  - php: nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
